### ISSUE TITLE
Unable to run bot, app crashes right away

### ISSUE THREAD

**Issue by almagest** [pylaligand/destiny-slack-bot#188]
Just trying to work with the online command right now. Created the bot, added all config vars, followed all directions. App crashes, returns 503. Not sure how to proceed. Any help would be appreciated. Thanks!

Config vars

![dry-dusk-31210_ _settings___heroku](https://cloud.githubusercontent.com/assets/337852/25069002/cdced7ce-2239-11e7-8a41-ded68a2315a7.jpg)

Errors:

```
2017-04-16T05:13:49.699775+00:00 app[web.1]: #3      _FutureListener.handleValue (dart:async/future_impl.dart:131)
2017-04-16T05:13:49.699776+00:00 app[web.1]: #4      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
2017-04-16T05:13:49.699777+00:00 app[web.1]: #5      _Future._propagateToListeners (dart:async/future_impl.dart:667)
2017-04-16T05:13:49.699777+00:00 app[web.1]: #6      _Future._completeWithValue (dart:async/future_impl.dart:477)
2017-04-16T05:13:49.699778+00:00 app[web.1]: #7      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
2017-04-16T05:13:49.699779+00:00 app[web.1]: #8      _microtaskLoop (dart:async/schedule_microtask.dart:41)
2017-04-16T05:13:49.699779+00:00 app[web.1]: #9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
2017-04-16T05:13:49.699780+00:00 app[web.1]: #10     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
2017-04-16T05:13:49.699781+00:00 app[web.1]: #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
2017-04-16T05:13:49.820946+00:00 heroku[web.1]: State changed from starting to crashed
2017-04-16T05:14:39.034168+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=dry-dusk-31210.herokuapp.com request_id=1677075a-af41-4a9c-814e-28d135f4b47b fwd="205.178.49.33" dyno= connect= service= status=503 bytes= protocol=https
```

**Comment by pylaligand** [comment]
Have you tried running it locally first?

**Comment by almagest** [comment]
No, that would be the right way to do this though. I'll play around tonight.

**Comment by almagest** [comment]
Turns out I was missing lots of required parameters not mentioned in the README.

**Comment by almagest** [comment]
```
TWITCH_CLIENT_ID
TWITCH_STREAMERS
THE_HUNDRED_AUTH_TOKEN
THE_HUNDRED_GROUP_ID
SLACK_CLIENT_ID
SLACK_CLIENT_SECRET
SLACK_VERIFICATION_TOKEN
```

**Comment by pylaligand** [comment]
I really need to make all of these features opt-in. I'll try to look into it soon.

**Comment by gugahoi** [comment]
where did you find the `SLACK_CLIENT_ID`?

**Comment by gugahoi** [comment]
so it seems like I need to create a slack app, a slash command as well as a bot to get this application to work?

**Comment by almagest** [comment]
I added it to my config vars and left the value blank and it works fine.

On Tue, Apr 25, 2017 at 11:29 PM, Gustavo Hoirisch <notifications@github.com

**Comment by pylaligand** [comment]
This bot is now deprecated in favor of https://github.com/pylaligand/destiny2-slack-bot.
