### ISSUE TITLE
"online" command fails

### ISSUE THREAD

**Issue by gugahoi** [pylaligand/destiny-slack-bot#189]
When trying `/online psn` (as well as some other commands that need to query destiny's database) I get the following error:

```
2017-04-26T09:31:12.297795+00:00 app[web.1]: INFO: 2017-04-26 09:31:12.297749: DestinySlackBot: 2017-04-26 09:31:09.794596	0:00:02.503101	POST	[200]	/commands/online
2017-04-26T09:31:13.763740+00:00 app[web.1]: INFO: 2017-04-26 09:31:13.763650: BungieDatabase: Database connection closed
2017-04-26T09:31:13.767046+00:00 app[web.1]: SEVERE: 2017-04-26 09:31:13.766910: DestinySlackBot: Oh noes! ERROR 42P01 relation "activity" does not exist #0      BungieDatabase.getActivity (file:///app/lib/bungie_database.dart:145:27)
2017-04-26T09:31:13.767048+00:00 app[web.1]: <asynchronous suspension>
2017-04-26T09:31:13.767049+00:00 app[web.1]: #1      OnlineHandler.handle.<anonymous closure> (file:///app/lib/online_handler.dart:53:50)
2017-04-26T09:31:13.767049+00:00 app[web.1]: <asynchronous suspension>
2017-04-26T09:31:13.767050+00:00 app[web.1]: #2      MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
2017-04-26T09:31:13.767050+00:00 app[web.1]: #3      ListIterator.moveNext (dart:_internal/iterable.dart:342)
2017-04-26T09:31:13.767051+00:00 app[web.1]: #4      Future.wait (dart:async/future.dart:336)
2017-04-26T09:31:13.767052+00:00 app[web.1]: #5      OnlineHandler.handle (file:///app/lib/online_handler.dart:49:20)
2017-04-26T09:31:13.767053+00:00 app[web.1]: <asynchronous suspension>
2017-04-26T09:31:13.767053+00:00 app[web.1]: #6      SlackCommandHandler._handleRequest (file:///app/lib/slack_command_handler.dart:48:5)
2017-04-26T09:31:13.767054+00:00 app[web.1]: <asynchronous suspension>
2017-04-26T09:31:13.767055+00:00 app[web.1]: #7      DefaultSegmentRouter.handle (package:shelf_route/src/default_segment_router.dart:31:25)
2017-04-26T09:31:13.767055+00:00 app[web.1]: <asynchronous suspension>
2017-04-26T09:31:13.767056+00:00 app[web.1]: #8      _BaseRoute.handle (package:shelf_route/src/route_impl.dart:27:21)
2017-04-26T09:31:13.767057+00:00 app[web.1]: #9      RequestRouterImpl._createHandler.<anonymous closure> (package:shelf_route/src/route_impl.dart:112:28)
2017-04-26T09:31:13.767058+00:00 app[web.1]: #10     DefaultSegmentRouter.handle (package:shelf_route/src/default_segment_router.dart:31:25)
2017-04-26T09:31:13.767058+00:00 app[web.1]: <asynchronous suspension>
2017-04-26T09:31:13.767059+00:00 app[web.1]: #11     _BaseRoute.handle (package:shelf_route/src/route_impl.dart:27:21)
2017-04-26T09:31:13.767060+00:00 app[web.1]: #12     RequestRouterImpl._createHandler.<anonymous closure> (package:shelf_route/src/route_impl.dart:112:28)
2017-04-26T09:31:13.767061+00:00 app[web.1]: #13     SlackVerificationMiddleware.get.<anonymous closure>.<anonymous closure> (file:///app/lib/slack_verification_middleware.dart:36:25)
2017-04-26T09:31:13.767061+00:00 app[web.1]: <asynchronous suspension>
2017-04-26T09:31:13.767062+00:00 app[web.1]: #14     BungieMiddleWare.get.<anonymous closure>.<anonymous closure> (file:///app/lib/bungie_middleware.dart:14:25)
2017-04-26T09:31:13.767063+00:00 app[web.1]: #15     DefaultSegmentRouter.handle (package:shelf_route/src/default_segment_router.dart:31:25)
2017-04-26T09:31:13.767064+00:00 app[web.1]: <asynchronous suspension>
2017-04-26T09:31:13.767064+00:00 app[web.1]: #16     _BaseRoute.handle (package:shelf_route/src/route_impl.dart:27:21)
2017-04-26T09:31:13.767065+00:00 app[web.1]: #17     RequestRouterImpl._createHandler.<anonymous closure> (package:shelf_route/src/route_impl.dart:112:28)
2017-04-26T09:31:13.767066+00:00 app[web.1]: #18     SlackClientMiddleware.get.<anonymous closure>.<anonymous closure> (file:///app/lib/slack_client_middleware.dart:12:25)
2017-04-26T09:31:13.767066+00:00 app[web.1]: <asynchronous suspension>
2017-04-26T09:31:13.767067+00:00 app[web.1]: #19     logRequests.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:shelf/src/middleware/logger.dart:30:46)
2017-04-26T09:31:13.767067+00:00 app[web.1]: #20     Future.Future.sync (dart:async/future.dart:208)
2017-04-26T09:31:13.767068+00:00 app[web.1]: #21     logRequests.<anonymous closure>.<anonymous closure> (package:shelf/src/middleware/logger.dart:30:16)
2017-04-26T09:31:13.767069+00:00 app[web.1]: #22     DefaultSegmentRouter.handle (package:shelf_route/src/default_segment_router.dart:31:25)
2017-04-26T09:31:13.767069+00:00 app[web.1]: <asynchronous suspension>
2017-04-26T09:31:13.767070+00:00 app[web.1]: #23     _BaseRoute.handle (package:shelf_route/src/route_impl.dart:27:21)
2017-04-26T09:31:13.767071+00:00 app[web.1]: #24     RequestRouterImpl._createHandler.<anonymous closure> (package:shelf_route/src/route_impl.dart:112:28)
2017-04-26T09:31:13.767071+00:00 app[web.1]: #25     DefaultSegmentRouter.handle (package:shelf_route/src/default_segment_router.dart:31:25)
2017-04-26T09:31:13.767072+00:00 app[web.1]: <asynchronous suspension>
2017-04-26T09:31:13.767073+00:00 app[web.1]: #26     _BaseRoute.handle (package:shelf_route/src/route_impl.dart:27:21)
2017-04-26T09:31:13.767073+00:00 app[web.1]: #27     _BaseRoute.createHandler.<anonymous closure> (package:shelf_route/src/route_impl.dart:32:22)
2017-04-26T09:31:13.767074+00:00 app[web.1]: <asynchronous suspension>
2017-04-26T09:31:13.767075+00:00 app[web.1]: #28     handleRequest (package:shelf/shelf_io.dart:78:29)
2017-04-26T09:31:13.767075+00:00 app[web.1]: <asynchronous suspension>
2017-04-26T09:31:13.767076+00:00 app[web.1]: #29     serveRequests.<anonymous closure>.<anonymous closure> (package:shelf/shelf_io.dart:54:34)
2017-04-26T09:31:13.767076+00:00 app[web.1]: #30     _rootRunUnary (dart:async/zone.dart:1128)
2017-04-26T09:31:13.767077+00:00 app[web.1]: #31     _CustomZone.runUnary (dart:async/zone.dart:1012)
2017-04-26T09:31:13.767077+00:00 app[web.1]: #32     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
2017-04-26T09:31:13.767078+00:00 app[web.1]: #33     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
2017-04-26T09:31:13.767079+00:00 app[web.1]: #34     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
2017-04-26T09:31:13.767079+00:00 app[web.1]: #35     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:757)
2017-04-26T09:31:13.767080+00:00 app[web.1]: #36     _StreamController._add (dart:async/stream_controller.dart:628)
2017-04-26T09:31:13.767081+00:00 app[web.1]: #37     _StreamController.add (dart:async/stream_controller.dart:574)
2017-04-26T09:31:13.767082+00:00 app[web.1]: #38     _HttpServer._handleRequest (dart:io/http_impl.dart:2343)
2017-04-26T09:31:13.767082+00:00 app[web.1]: #39     _HttpConnection._HttpConnection.<anonymous closure> (dart:io/http_impl.dart:2096)
2017-04-26T09:31:13.767083+00:00 app[web.1]: #40     _rootRunUnary (dart:async/zone.dart:1128)
2017-04-26T09:31:13.767083+00:00 app[web.1]: #41     _CustomZone.runUnary (dart:async/zone.dart:1012)
2017-04-26T09:31:13.767084+00:00 app[web.1]: #42     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
2017-04-26T09:31:13.767087+00:00 app[web.1]: #43     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
2017-04-26T09:31:13.767088+00:00 app[web.1]: #44     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
2017-04-26T09:31:13.767088+00:00 app[web.1]: #45     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:757)
2017-04-26T09:31:13.767089+00:00 app[web.1]: #46     _StreamController._add (dart:async/stream_controller.dart:628)
2017-04-26T09:31:13.767089+00:00 app[web.1]: #47     _StreamController.add (dart:async/stream_controller.dart:574)
2017-04-26T09:31:13.767090+00:00 app[web.1]: #48     _HttpParser._headersEnd (dart:io/http_parser.dart:403)
2017-04-26T09:31:13.767090+00:00 app[web.1]: #49     _HttpParser._doParse (dart:io/http_parser.dart:711)
2017-04-26T09:31:13.767090+00:00 app[web.1]: #50     _HttpParser._parse (dart:io/http_parser.dart:332)
2017-04-26T09:31:13.767091+00:00 app[web.1]: #51     _HttpParser._onData (dart:io/http_parser.dart:821)
2017-04-26T09:31:13.767091+00:00 app[web.1]: #52     _rootRunUnary (dart:async/zone.dart:1128)
2017-04-26T09:31:13.767092+00:00 app[web.1]: #53     _CustomZone.runUnary (dart:async/zone.dart:1012)
2017-04-26T09:31:13.767092+00:00 app[web.1]: #54     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
2017-04-26T09:31:13.767092+00:00 app[web.1]: #55     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
2017-04-26T09:31:13.767093+00:00 app[web.1]: #56     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
2017-04-26T09:31:13.767093+00:00 app[web.1]: #57     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:757)
2017-04-26T09:31:13.767094+00:00 app[web.1]: #58     _StreamController._add (dart:async/stream_controller.dart:628)
2017-04-26T09:31:13.767094+00:00 app[web.1]: #59     _StreamController.add (dart:async/stream_controller.dart:574)
2017-04-26T09:31:13.767095+00:00 app[web.1]: #60     _Socket._onData (dart:io-patch/socket_patch.dart:1617)
2017-04-26T09:31:13.767095+00:00 app[web.1]: #61     _rootRunUnary (dart:async/zone.dart:1132)
2017-04-26T09:31:13.767095+00:00 app[web.1]: #62     _CustomZone.runUnary (dart:async/zone.dart:1012)
2017-04-26T09:31:13.767096+00:00 app[web.1]: #63     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
2017-04-26T09:31:13.767096+00:00 app[web.1]: #64     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
2017-04-26T09:31:13.767097+00:00 app[web.1]: #65     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
2017-04-26T09:31:13.767097+00:00 app[web.1]: #66     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:757)
2017-04-26T09:31:13.767100+00:00 app[web.1]: #67     _StreamController._add (dart:async/stream_controller.dart:628)
2017-04-26T09:31:13.767101+00:00 app[web.1]: #68     _StreamController.add (dart:async/stream_controller.dart:574)
2017-04-26T09:31:13.767101+00:00 app[web.1]: #69     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1203)
2017-04-26T09:31:13.767101+00:00 app[web.1]: #70     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:760)
2017-04-26T09:31:13.767102+00:00 app[web.1]: #71     _microtaskLoop (dart:async/schedule_microtask.dart:41)
2017-04-26T09:31:13.767111+00:00 app[web.1]: #72     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
2017-04-26T09:31:13.767112+00:00 app[web.1]: #73     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
2017-04-26T09:31:13.767112+00:00 app[web.1]: #74     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)
2017-04-26T09:31:13.767113+00:00 app[web.1]: 
Disconnected from log stream. There may be events happening that you do not see here! Attempting to reconnect...
2017-04-26T09:31:13.767097+00:00 app[web.1]: #65     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
2017-04-26T09:31:13.767097+00:00 app[web.1]: #66     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:757)
2017-04-26T09:31:13.767100+00:00 app[web.1]: #67     _StreamController._add (dart:async/stream_controller.dart:628)
2017-04-26T09:31:13.767101+00:00 app[web.1]: #68     _StreamController.add (dart:async/stream_controller.dart:574)
2017-04-26T09:31:13.767101+00:00 app[web.1]: #69     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1203)
2017-04-26T09:31:13.767101+00:00 app[web.1]: #70     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:760)
2017-04-26T09:31:13.767102+00:00 app[web.1]: #71     _microtaskLoop (dart:async/schedule_microtask.dart:41)
2017-04-26T09:31:13.767111+00:00 app[web.1]: #72     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
2017-04-26T09:31:13.767112+00:00 app[web.1]: #73     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
2017-04-26T09:31:13.767112+00:00 app[web.1]: #74     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)
```

**Comment by pylaligand** [comment]
Is your local database provisioned?

**Comment by gugahoi** [comment]
I got it to work, my database wasnt set up properly inside the container. I also opened up an issue in you sqllite repo as that library wasnt erroring when running inside docker. I feel like this project would greatly benefit of a docker-compose file to get a local environment up and running, would happily create a PR for it.

**Comment by pylaligand** [comment]
I know very little about docker but a PR would be very welcome!

**Comment by scotticus** [comment]
I know this is closed, but I have a similar issue. I just don't know what you mean by "Is your local database provisioned?" I think I missed something in the README, or some basic knowledge was assumed that I do not have.
